# Generated by Django 2.0.6 on 2018-10-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20181019_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'depart__code': 'training', 'roles__code': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_user', to='system.UserInfo', verbose_name='班主任'),
        ),
    ]
