# Generated by Django 2.0.6 on 2018-10-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20181022_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.IntegerField(blank=True, choices=[(1, '重点大学'), (2, '普通本科'), (3, '独立院校'), (4, '民办本科'), (5, '大专'), (6, '民办专科'), (7, '高中'), (8, '其他')], null=True, verbose_name='学历')),
                ('graduation_school', models.CharField(blank=True, max_length=64, null=True, verbose_name='毕业学校')),
                ('major', models.CharField(blank=True, max_length=64, null=True, verbose_name='所学专业')),
                ('experience', models.IntegerField(blank=True, choices=[(1, '在校生'), (2, '应届毕业'), (3, '半年以内'), (4, '半年至一年'), (5, '一年至三年'), (6, '三年至五年'), (7, '五年以上')], null=True, verbose_name='工作经验')),
                ('work_status', models.IntegerField(blank=True, choices=[(1, '在职'), (2, '无业')], default=1, null=True, verbose_name='职业状态')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='目前就职公司')),
                ('salary', models.CharField(blank=True, max_length=64, null=True, verbose_name='当前薪资')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='graduation_school',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='major',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='work_status',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Customer', verbose_name='客户主ID'),
        ),
    ]
